### ISSUE TITLE
readthedocsのpythonバージョン修正

### ISSUE THREAD

**Issue by tarao1006** [tarao1006/pyheatintegration#3]
readthedocsのビルドでpython3.7が使用されているため、warningが生じ、APIが正しく表示されていない。 `.readthedocs.yaml` の中で `testing` を指定しているため、python3.9が使われるはずであるが、ログを見ると3.7が使用されている。

**Comment by tarao1006** [comment]
ビルドイメージの指定だけではなく、明示的にpythonのバージョンを指定する必要があり。

```yaml
...
python:
   version: 3.9

build:
  image: testing
```
